apiVersion: v1
kind: Service
metadata:
  name: zap-operator-metrics
  namespace: zap-system
  labels:
    app: zap-operator
spec:
  selector:
    app: zap-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
