apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zap-operator-role
rules:
  - apiGroups: ["spaceship.com"]
    resources: ["zapscans", "zapscans/status", "zapscheduledscans", "zapscheduledscans/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
